swagger: '2.0'
info:
  description: >
    lexneo4j is a neo4j interface application The base path for all the APIs is
    "/api/v1".
  title: lexneo4j
  version: 1.0.0
tags:
  - name: health
    description: Check if lexneo4j is healthy
x-tagGroups:
  - name: lexneo4j Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /health:
    get:
      tags:
        - health
      operationId: getHealth
      description: Check if Flagr is healthy
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /cypher:
    post:
      tags:
        - app
      summary: Run a custom cypher command
      operationId: doCypher
      parameters:
        - in: body
          name: body
          description: readonly cypher command
          required: true
          schema:
            type: object
            properties:
              cmd:
                description: cypher command
                type: string
                minLength: 1
      responses:
        '200':
          description: cypher command result
          schema:
            type: object
            properties:
              result:
                description: cypher command result
                type: array
                items:
                  type: object
                  properties:
                    line:
                      type: string
                      minLength: 1
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /movies:
    get:
      tags:
        - app
      summary: 'App: List movies'
      operationId: listMovies
      responses:
        '200':
          description: list all movies
          schema:
            type: object
            properties:
              movies:
                type: array
                items:
                  $ref: '#/definitions/movie'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  health:
    type: object
    properties:
      status:
        type: string
  cypher:
    type: object
    required:
      - cmd
    properties:
      cmd:
        description: cypher command
        type: string
        minLength: 1
  movie:
    type: object
    required:
      - title
    properties:
      title:
        description: movie title
        type: string
        minLength: 1
      released:
        description: released year
        type: integer
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
